/// Kenya county -> subcounty lookup, used by the dependent
/// dropdowns on the farm registration form.
///
/// Draft list based on constituency names (47 counties, 290
/// subcounties). To be reconciled with FCL's own administrative
/// coding during the testing phase.
class KenyaLocations {
  KenyaLocations._();

  static const Map<String, List<String>> countySubcounties = {
    'Baringo': [
      'Tiaty',
      'Baringo North',
      'Baringo Central',
      'Baringo South',
      'Mogotio',
      'Eldama Ravine',
    ],
    'Bomet': [
      'Sotik',
      'Chepalungu',
      'Bomet East',
      'Bomet Central',
      'Konoin',
    ],
    'Bungoma': [
      'Mt Elgon',
      'Sirisia',
      'Kabuchai',
      'Bumula',
      'Kanduyi',
      'Webuye East',
      'Webuye West',
      'Kimilili',
      'Tongaren',
    ],
    'Busia': [
      'Teso North',
      'Teso South',
      'Nambale',
      'Matayos',
      'Butula',
      'Funyula',
      'Budalangi',
    ],
    'Elgeyo-Marakwet': [
      'Marakwet East',
      'Marakwet West',
      'Keiyo North',
      'Keiyo South',
    ],
    'Embu': [
      'Manyatta',
      'Runyenjes',
      'Mbeere South',
      'Mbeere North',
    ],
    'Garissa': [
      'Garissa Township',
      'Balambala',
      'Lagdera',
      'Dadaab',
      'Fafi',
      'Ijara',
    ],
    'Homa Bay': [
      'Kasipul',
      'Kabondo Kasipul',
      'Karachuonyo',
      'Rangwe',
      'Homa Bay Town',
      'Ndhiwa',
      'Suba North',
      'Suba South',
    ],
    'Isiolo': [
      'Isiolo North',
      'Isiolo South',
    ],
    'Kajiado': [
      'Kajiado North',
      'Kajiado Central',
      'Kajiado East',
      'Kajiado West',
      'Kajiado South',
    ],
    'Kakamega': [
      'Lugari',
      'Likuyani',
      'Malava',
      'Lurambi',
      'Navakholo',
      'Mumias West',
      'Mumias East',
      'Matungu',
      'Butere',
      'Khwisero',
      'Shinyalu',
      'Ikolomani',
    ],
    'Kericho': [
      'Ainamoi',
      'Belgut',
      'Bureti',
      'Kipkelion East',
      'Kipkelion West',
      'Sigowet/Soin',
    ],
    'Kiambu': [
      'Gatundu South',
      'Gatundu North',
      'Juja',
      'Thika Town',
      'Ruiru',
      'Githunguri',
      'Kiambu',
      'Kiambaa',
      'Kabete',
      'Kikuyu',
      'Limuru',
      'Lari',
    ],
    'Kilifi': [
      'Kilifi North',
      'Kilifi South',
      'Kaloleni',
      'Rabai',
      'Ganze',
      'Malindi',
      'Magarini',
    ],
    'Kirinyaga': [
      'Mwea',
      'Gichugu',
      'Ndia',
      'Kirinyaga Central',
    ],
    'Kisii': [
      'Bonchari',
      'South Mugirango',
      'Bomachoge Borabu',
      'Bobasi',
      'Bomachoge Chache',
      'Nyaribari Masaba',
      'Nyaribari Chache',
      'Kitutu Chache North',
      'Kitutu Chache South',
    ],
    'Kisumu': [
      'Kisumu East',
      'Kisumu West',
      'Kisumu Central',
      'Seme',
      'Nyando',
      'Muhoroni',
      'Nyakach',
    ],
    'Kitui': [
      'Mwingi North',
      'Mwingi West',
      'Mwingi Central',
      'Kitui West',
      'Kitui Rural',
      'Kitui Central',
      'Kitui East',
      'Kitui South',
    ],
    'Kwale': [
      'Msambweni',
      'Lunga Lunga',
      'Matuga',
      'Kinango',
    ],
    'Laikipia': [
      'Laikipia West',
      'Laikipia East',
      'Laikipia North',
    ],
    'Lamu': [
      'Lamu East',
      'Lamu West',
    ],
    'Machakos': [
      'Masinga',
      'Yatta',
      'Kangundo',
      'Matungulu',
      'Kathiani',
      'Mavoko',
      'Machakos Town',
      'Mwala',
    ],
    'Makueni': [
      'Mbooni',
      'Kilome',
      'Kaiti',
      'Makueni',
      'Kibwezi West',
      'Kibwezi East',
    ],
    'Mandera': [
      'Mandera West',
      'Banissa',
      'Mandera North',
      'Mandera South',
      'Mandera East',
      'Lafey',
    ],
    'Marsabit': [
      'Moyale',
      'North Horr',
      'Saku',
      'Laisamis',
    ],
    'Meru': [
      'Igembe South',
      'Igembe Central',
      'Igembe North',
      'Tigania West',
      'Tigania East',
      'North Imenti',
      'Buuri',
      'Central Imenti',
      'South Imenti',
    ],
    'Migori': [
      'Rongo',
      'Awendo',
      'Suna East',
      'Suna West',
      'Uriri',
      'Nyatike',
      'Kuria West',
      'Kuria East',
    ],
    'Mombasa': [
      'Changamwe',
      'Jomvu',
      'Kisauni',
      'Nyali',
      'Likoni',
      'Mvita',
    ],
    'Murang\'a': [
      'Kangema',
      'Mathioya',
      'Kiharu',
      'Kigumo',
      'Maragwa',
      'Kandara',
      'Gatanga',
    ],
    'Nairobi': [
      'Westlands',
      'Dagoretti North',
      'Dagoretti South',
      'Langata',
      'Kibra',
      'Roysambu',
      'Kasarani',
      'Ruaraka',
      'Embakasi South',
      'Embakasi North',
      'Embakasi Central',
      'Embakasi East',
      'Embakasi West',
      'Makadara',
      'Kamukunji',
      'Starehe',
      'Mathare',
    ],
    'Nakuru': [
      'Molo',
      'Njoro',
      'Naivasha',
      'Gilgil',
      'Kuresoi South',
      'Kuresoi North',
      'Subukia',
      'Rongai',
      'Bahati',
      'Nakuru Town West',
      'Nakuru Town East',
    ],
    'Nandi': [
      'Tinderet',
      'Aldai',
      'Nandi Hills',
      'Chesumei',
      'Emgwen',
      'Mosop',
    ],
    'Narok': [
      'Kilgoris',
      'Emurua Dikirr',
      'Narok North',
      'Narok East',
      'Narok South',
      'Narok West',
    ],
    'Nyamira': [
      'Kitutu Masaba',
      'West Mugirango',
      'North Mugirango',
      'Borabu',
    ],
    'Nyandarua': [
      'Kinangop',
      'Kipipiri',
      'Ol Kalou',
      'Ol Jorok',
      'Ndaragwa',
    ],
    'Nyeri': [
      'Tetu',
      'Kieni',
      'Mathira',
      'Othaya',
      'Mukurweini',
      'Nyeri Town',
    ],
    'Samburu': [
      'Samburu West',
      'Samburu North',
      'Samburu East',
    ],
    'Siaya': [
      'Ugenya',
      'Ugunja',
      'Alego Usonga',
      'Gem',
      'Bondo',
      'Rarieda',
    ],
    'Taita Taveta': [
      'Taveta',
      'Wundanyi',
      'Mwatate',
      'Voi',
    ],
    'Tana River': [
      'Garsen',
      'Galole',
      'Bura',
    ],
    'Tharaka-Nithi': [
      'Maara',
      'Chuka/Igambang\'ombe',
      'Tharaka',
    ],
    'Trans Nzoia': [
      'Kwanza',
      'Endebess',
      'Saboti',
      'Kiminini',
      'Cherangany',
    ],
    'Turkana': [
      'Turkana North',
      'Turkana West',
      'Turkana Central',
      'Loima',
      'Turkana South',
      'Turkana East',
    ],
    'Uasin Gishu': [
      'Soy',
      'Turbo',
      'Moiben',
      'Ainabkoi',
      'Kapseret',
      'Kesses',
    ],
    'Vihiga': [
      'Vihiga',
      'Sabatia',
      'Hamisi',
      'Luanda',
      'Emuhaya',
    ],
    'Wajir': [
      'Wajir North',
      'Wajir East',
      'Tarbaj',
      'Wajir West',
      'Eldas',
      'Wajir South',
    ],
    'West Pokot': [
      'Kapenguria',
      'Sigor',
      'Kacheliba',
      'Pokot South',
    ],
  };

  /// All 47 counties, alphabetical — feeds the county dropdown.
  static List<String> get counties =>
      countySubcounties.keys.toList();

  /// Subcounties for one county; empty list if none selected.
  static List<String> subcountiesOf(String? county) =>
      county == null ? const [] : (countySubcounties[county] ?? const []);
}
