// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8Lm2teu5fO3ML4O3VkmCBhSft27cjO78',
    appId: '1:65254725041:web:1fde991781a610f77c1990',
    messagingSenderId: '65254725041',
    projectId: 'cm-beef-app1',
    authDomain: 'cm-beef-app1.firebaseapp.com',
    storageBucket: 'cm-beef-app1.firebasestorage.app',
    measurementId: 'G-R99HCKWX2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbgNcrJhY6Rroc1u9RZRRO5mwK8go7tWM',
    appId: '1:65254725041:android:83f6c40c1b6170057c1990',
    messagingSenderId: '65254725041',
    projectId: 'cm-beef-app1',
    storageBucket: 'cm-beef-app1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmvuX_XPezYgavKKKV1-am-Ts5olyDcjc',
    appId: '1:65254725041:ios:3c44c45c70d19d017c1990',
    messagingSenderId: '65254725041',
    projectId: 'cm-beef-app1',
    storageBucket: 'cm-beef-app1.firebasestorage.app',
    iosBundleId: 'com.example.cmDemo2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmvuX_XPezYgavKKKV1-am-Ts5olyDcjc',
    appId: '1:65254725041:ios:3c44c45c70d19d017c1990',
    messagingSenderId: '65254725041',
    projectId: 'cm-beef-app1',
    storageBucket: 'cm-beef-app1.firebasestorage.app',
    iosBundleId: 'com.example.cmDemo2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8Lm2teu5fO3ML4O3VkmCBhSft27cjO78',
    appId: '1:65254725041:web:74d8bc82df01a4747c1990',
    messagingSenderId: '65254725041',
    projectId: 'cm-beef-app1',
    authDomain: 'cm-beef-app1.firebaseapp.com',
    storageBucket: 'cm-beef-app1.firebasestorage.app',
    measurementId: 'G-H06M1YNY0J',
  );
}
